name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com/
          scope: ${{ github.repository_owner }}
      - run: npm ci
      - run: npm publish
        env:
          token: ${{ secrets.CLOUD_DEVOPS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.CLOUD_DEVOPS_TOKEN }}
